"""Seed the bundled Gitea with the demo `fleet` repo via its API.

The admin token is generated by the one-shot `gitea-init` service and written to
a shared volume (no token committed to git). We create the repo (auto_init) and
upload every file under the seed dir through the contents API — no git push
credentials needed.
"""
import base64
import os
import time

import requests

from . import config


def _token() -> str:
    if os.path.exists(config.GITEA_TOKEN_FILE):
        t = open(config.GITEA_TOKEN_FILE).read().strip()
        if t:
            return t
    return os.environ.get("GITEA_TOKEN", "").strip()


def wait_ready(timeout: int = 150) -> bool:
    start = time.time()
    while time.time() - start < timeout:
        try:
            r = requests.get(config.GITEA_URL + "/api/v1/version", timeout=4)
            if r.ok:
                return True
        except Exception:
            pass
        time.sleep(3)
    return False


def _seed_files():
    files = []
    for root, _, names in os.walk(config.SEED_DIR):
        for n in names:
            full = os.path.join(root, n)
            rel = os.path.relpath(full, config.SEED_DIR).replace(os.sep, "/")
            with open(full) as f:
                files.append((rel, f.read()))
    return files


def _put_file(headers, owner, repo, path, content):
    url = f"{config.GITEA_URL}/api/v1/repos/{owner}/{repo}/contents/{path}"
    body = {"content": base64.b64encode(content.encode()).decode(), "message": f"seed {path}", "branch": "main"}
    existing = requests.get(url, headers=headers, params={"ref": "main"}, timeout=8)
    if existing.ok:
        body["sha"] = existing.json().get("sha")
        requests.put(url, headers=headers, json=body, timeout=8)
    else:
        requests.post(url, headers=headers, json=body, timeout=8)


def seed() -> bool:
    token = _token()
    if not token:
        print("gitea: no admin token available; skipping seed")
        return False
    headers = {"Authorization": f"token {token}", "Content-Type": "application/json"}
    owner, repo = config.GITEA_ADMIN_USER, config.GITEA_REPO

    exists = requests.get(f"{config.GITEA_URL}/api/v1/repos/{owner}/{repo}", headers=headers, timeout=8)
    if exists.status_code == 404:
        requests.post(
            f"{config.GITEA_URL}/api/v1/user/repos", headers=headers, timeout=10,
            json={"name": repo, "private": False, "auto_init": True,
                  "default_branch": "main", "description": "Rudder demo fleet repo"},
        )
        time.sleep(1.5)

    for path, content in _seed_files():
        try:
            _put_file(headers, owner, repo, path, content)
        except Exception as e:
            print(f"gitea: failed to seed {path}: {e}")
    print(f"gitea: seeded {owner}/{repo}")
    return True
